import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T17:43:22.119Z

test.describe('Dashboard Access', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to http://localhost:3000/dashboard
    await page.goto('http://localhost:3000/dashboard');

    // Take a snapshot of the page
    await expect(page).toHaveScreenshot();

  });
});
