import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T18:28:21.772Z

test.describe('Scenario: Dashboard page loads', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to /dashboard
    await page.goto('http://localhost:3000/dashboard');

    // Assert page contains "Welcome to your dashboard"
    await expect(page.getByText('Welcome to your dashboard')).toBeVisible();

    // Assert page contains "Recent Activities"
    await expect(page.getByText('Recent Activities')).toBeVisible();

  });
});
