import { test, expect } from '@playwright/test';

// Auto-generated by SentinelQA Pipeline
// 2026-03-13T18:45:25.379Z

test.describe('Scenario: Auth page renders', () => {
  test('should pass all checks', async ({ page }) => {
    await page.goto('http://localhost:3000');

    // Navigate to /auth
    await page.goto('http://localhost:3000/auth');

    // Assert page contains "Sign in"
    await expect(page.getByText('Sign in')).toBeVisible();

    // Assert page contains "Continue with GitHub"
    await expect(page.getByText('Continue with GitHub')).toBeVisible();

  });
});
