// ============================================================================
// SentinelQA — AI Engine Client
//
// Abstraction layer between the orchestrator and the AI backend.
// Today: wraps the existing simulated test-plan generator as fallback.
// Tomorrow: calls Aaskar's Python FastAPI service (Claude / LangGraph).
//
// Toggle via environment variable:
//   AI_ENGINE_URL=http://ai-engine:5000   → use real service
//   (unset or empty)                      → use simulated fallback
// ============================================================================

import type { TestResult } from "./types";

// ── Types ───────────────────────────────────────────────────────────────────

export interface FailureAnalysis {
  rca_report: string;
  proposed_fix: string;
  confidence: number;
}

// ── AI Engine Client ────────────────────────────────────────────────────────

export class AIEngineClient {
  private baseUrl: string | null;

  constructor() {
    this.baseUrl = process.env.AI_ENGINE_URL || null;
  }

  get isConnected(): boolean {
    return this.baseUrl !== null;
  }

  // ── Test Plan Generation (Architect Agent) ────────────────────────────────

  async generateTestPlan(
    codeContext: string,
    changedFiles: string[],
    targetUrl: string
  ): Promise<string> {
    if (this.baseUrl) {
      const response = await this.callRemote<{ test_plan: string; provider: string }>("/generate-test-plan", {
        code_context: codeContext,
        changed_files: changedFiles,
        target_url: targetUrl,
      });
      console.log(`[AI Engine] Test plan generated by: ${response.provider}`);
      return response.test_plan;
    }
    return this.simulatedTestPlan(codeContext, targetUrl);
  }

  // ── Failure Analysis (Healer Agent) ───────────────────────────────────────

  async analyzeFailure(
    testResults: TestResult[],
    codeContext: string,
    diff: string
  ): Promise<FailureAnalysis> {
    if (this.baseUrl) {
      return this.callRemote("/analyze-failure", {
        test_results: testResults,
        code_context: codeContext,
        diff,
      });
    }
    return this.simulatedAnalysis(testResults);
  }

  // ── Remote call to Aaskar's service ───────────────────────────────────────

  private async callRemote<T>(endpoint: string, body: unknown): Promise<T> {
    const url = `${this.baseUrl}${endpoint}`;
    const res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(30_000),
    });

    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`AI Engine error (${res.status}): ${text}`);
    }

    return res.json() as Promise<T>;
  }

  // ── Simulated Fallbacks ───────────────────────────────────────────────────

  private simulatedTestPlan(codeContext: string, targetUrl: string): string {
    const hasAuth = codeContext.toLowerCase().includes("auth");
    const hasDashboard = codeContext.toLowerCase().includes("dashboard");

    let plan = `## Auto-Generated Test Plan
### Application: ${targetUrl}
### Generated by: SentinelQA Architect Agent (simulated)
### Based on: Code analysis of repository

---

## Test Suite 1: Landing Page Verification
1. Navigate to ${targetUrl}
2. Take a snapshot of the page
3. Assert the page contains the main heading
`;

    if (hasAuth) {
      plan += `
## Test Suite 2: Authentication Page
1. Navigate to ${targetUrl}/auth
2. Take a snapshot of the page
3. Assert the page contains a login form
`;
    }

    if (hasDashboard) {
      plan += `
## Test Suite 3: Dashboard Access
1. Navigate to ${targetUrl}/dashboard
2. Take a snapshot of the page
`;
    }

    return plan;
  }

  private simulatedAnalysis(testResults: TestResult[]): FailureAnalysis {
    const failures = testResults.filter((r) => r.status === "failed");
    const errorSummary = failures
      .map((f) => `- ${f.name}: ${f.error ?? "unknown"}`)
      .join("\n");

    return {
      rca_report: `## Root Cause Analysis (Simulated)\n\n### Failed Tests\n${errorSummary}\n\n### Probable Cause\nUI element mismatch detected. The page structure may have changed after a recent deployment.\n\n### Recommendation\nVerify that the target elements still exist in the DOM with the expected accessibility labels.`,
      proposed_fix: "// Simulated fix — real fixes require AI analysis via Claude\n// Update selectors to match current DOM structure",
      confidence: 0.5,
    };
  }
}

// ── Singleton ───────────────────────────────────────────────────────────────

export const aiEngine = new AIEngineClient();
