// ============================================================================
// SentinelQA — Test Writer
//
// Converts AI-generated test plans + execution results into real Playwright
// test files (.spec.ts) that developers can review, run, and maintain.
// Also generates a rich PR body with results, snapshots, and pipeline steps.
// ============================================================================

import type { TestResult, TestRunOutput } from "./types";

// ── Types ───────────────────────────────────────────────────────────────────

export interface GeneratedTestFile {
  /** File path relative to repo root (e.g. tests/e2e/landing-page.spec.ts) */
  path: string;
  /** Full file content */
  content: string;
}

interface TestSuite {
  name: string;
  steps: string[];
}

// ── Test Code Generator ─────────────────────────────────────────────────────

/**
 * Parse the markdown test plan into individual test suites.
 */
function parseTestSuites(testPlan: string): TestSuite[] {
  const suites: TestSuite[] = [];
  let currentSuite: TestSuite | null = null;

  for (const line of testPlan.split("\n")) {
    const trimmed = line.trim();

    // Match suite headers: "## Test Suite 1: Landing Page" or "## 1. Landing Page"
    const suiteMatch = trimmed.match(/^##\s+(?:Test Suite \d+:\s*)?(?:\d+\.\s*)?(.+)/i);
    if (suiteMatch && !trimmed.startsWith("###")) {
      if (currentSuite) suites.push(currentSuite);
      currentSuite = { name: suiteMatch[1].trim(), steps: [] };
      continue;
    }

    // Match numbered steps
    const stepMatch = trimmed.match(/^(?:\d+\.\s+|-\s+)(.+)$/);
    if (stepMatch && currentSuite) {
      currentSuite.steps.push(stepMatch[1]);
    }
  }

  if (currentSuite) suites.push(currentSuite);
  return suites;
}

/**
 * Convert a suite name to a valid filename slug.
 */
function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 50);
}

/**
 * Convert a test step description into Playwright test code.
 * @param targetUrl - base URL used to resolve relative navigation targets
 */
function stepToCode(step: string, indent: string, targetUrl: string): string {
  const lower = step.toLowerCase();

  // Navigate
  const navMatch = step.match(/navigate\s+to\s+(\S+)/i);
  if (navMatch) {
    const target = navMatch[1];
    const isAbsolute = /^https?:\/\//i.test(target);
    const resolved = isAbsolute
      ? target
      : `${targetUrl.replace(/\/$/, "")}/${target.replace(/^\//, "")}`;
    return `${indent}await page.goto('${resolved}');`;
  }

  // Snapshot
  if (lower.includes("snapshot") || lower.includes("capture")) {
    return `${indent}await expect(page).toHaveScreenshot();`;
  }

  // Assert contains
  const assertMatch = step.match(/assert\s+(?:the\s+)?(?:page\s+)?contains?\s+["']?(.+?)["']?$/i);
  if (assertMatch) {
    const text = assertMatch[1].replace(/'/g, "\\'");
    return `${indent}await expect(page.getByText('${text}')).toBeVisible();`;
  }

  // Click
  const clickMatch = step.match(/click\s+(?:the\s+|on\s+)?["'](.+?)["']\s*(?:button|link|element)?/i);
  if (clickMatch) {
    return `${indent}await page.getByRole('button', { name: '${clickMatch[1]}' }).or(page.getByRole('link', { name: '${clickMatch[1]}' })).click();`;
  }
  if (lower.includes("click")) {
    const generic = step.replace(/^click\s+(?:the\s+|on\s+)?/i, "").replace(/\s*(?:button|link|element)\s*$/i, "");
    return `${indent}await page.getByText('${generic.replace(/'/g, "\\'")}').click();`;
  }

  // Type
  const typeMatch = step.match(/type\s+["'](.+?)["']\s+(?:into|in)\s+(?:the\s+)?(.+)/i);
  if (typeMatch) {
    const value = typeMatch[1].replace(/'/g, "\\'");
    const field = typeMatch[2].replace(/\s*field\s*$/i, "").trim();
    return `${indent}await page.getByLabel('${field}').or(page.getByPlaceholder('${field}')).fill('${value}');`;
  }

  // Wait
  const waitMatch = step.match(/wait\s+(?:for\s+)?(\d+)\s*(?:seconds?|ms)?/i);
  if (waitMatch) {
    let ms = parseInt(waitMatch[1], 10);
    if (lower.includes("second")) ms *= 1000;
    return `${indent}await page.waitForTimeout(${ms});`;
  }

  // Hover
  const hoverMatch = step.match(/hover\s+(?:over\s+)?(?:the\s+)?["']?(.+?)["']?$/i);
  if (hoverMatch) {
    return `${indent}await page.getByText('${hoverMatch[1].replace(/'/g, "\\'")}').hover();`;
  }

  // Fallback: comment
  return `${indent}// TODO: ${step}`;
}

/**
 * Generate a complete Playwright test file for a test suite.
 */
function generateSpecFile(suite: TestSuite, targetUrl: string): string {
  const lines: string[] = [];
  const indent = "  ";

  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`// Auto-generated by SentinelQA Pipeline`);
  lines.push(`// ${new Date().toISOString()}`);
  lines.push(``);
  lines.push(`test.describe('${suite.name.replace(/'/g, "\\'")}', () => {`);
  lines.push(`${indent}test('should pass all checks', async ({ page }) => {`);
  lines.push(`${indent}${indent}await page.goto('${targetUrl}');`);
  lines.push(``);

  for (const step of suite.steps) {
    lines.push(`${indent}${indent}// ${step}`);
    lines.push(stepToCode(step, `${indent}${indent}`, targetUrl));
    lines.push(``);
  }

  lines.push(`${indent}});`);
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}

// ── Public API ──────────────────────────────────────────────────────────────

/**
 * Generate Playwright test files from a test plan.
 */
export function generateTestFiles(
  testPlan: string,
  targetUrl: string
): GeneratedTestFile[] {
  const suites = parseTestSuites(testPlan);
  const files: GeneratedTestFile[] = [];

  for (const suite of suites) {
    if (suite.steps.length === 0) continue;
    const slug = toSlug(suite.name);
    files.push({
      path: `tests/e2e/${slug}.spec.ts`,
      content: generateSpecFile(suite, targetUrl),
    });
  }

  // Also write the raw test plan as markdown for reference
  files.push({
    path: `tests/e2e/TEST_PLAN.md`,
    content: `# SentinelQA — Auto-Generated Test Plan\n\n> Generated on ${new Date().toISOString()}\n\n${testPlan}\n`,
  });

  return files;
}

/**
 * Build a rich PR body with:
 * - Pipeline steps summary
 * - Test results table
 * - Accessibility snapshots from failures
 * - Generated test file listing
 */
export function buildPRBody(
  sessionId: string,
  testPlan: string,
  results: TestRunOutput,
  files: GeneratedTestFile[],
  codeContextLength: number
): string {
  const lines: string[] = [];

  // Header
  lines.push(`## 🛡️ SentinelQA — Auto-Generated Tests`);
  lines.push(``);
  lines.push(`**Session**: \`${sessionId}\``);
  lines.push(`**Generated**: ${new Date().toISOString()}`);
  lines.push(``);

  // Pipeline steps
  lines.push(`### 🔄 Pipeline Steps`);
  lines.push(``);
  lines.push(`| Step | Description | Status |`);
  lines.push(`|------|-------------|--------|`);
  lines.push(`| 1 | GitHub MCP — Read repository code (${codeContextLength} chars) | ✅ |`);
  lines.push(`| 2 | AI Engine — Generate test plan (${testPlan.split("\n").length} lines) | ✅ |`);
  lines.push(`| 3 | Playwright MCP — Execute tests in headless browser | ✅ |`);
  lines.push(`| 4 | Test Writer — Generate Playwright spec files | ✅ |`);
  lines.push(`| 5 | Courier — Push tests & open this PR | ✅ |`);
  lines.push(``);

  // Results summary
  const passRate = results.total > 0 ? ((results.passed / results.total) * 100).toFixed(0) : "0";
  lines.push(`### 📊 Test Results`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Tests | ${results.total} |`);
  lines.push(`| ✅ Passed | ${results.passed} |`);
  lines.push(`| ❌ Failed | ${results.failed} |`);
  lines.push(`| Pass Rate | ${passRate}% |`);
  lines.push(`| Duration | ${results.duration_ms}ms |`);
  lines.push(``);

  // Detailed results table
  lines.push(`### 📋 Step-by-Step Results`);
  lines.push(``);
  lines.push(`| # | Test Step | Status | Duration |`);
  lines.push(`|---|-----------|--------|----------|`);
  for (let i = 0; i < results.results.length; i++) {
    const r = results.results[i];
    const icon = r.status === "passed" ? "✅" : r.status === "failed" ? "❌" : "⏭️";
    const name = r.name.replace(/^Step \d+: /, "");
    lines.push(`| ${i + 1} | ${name} | ${icon} ${r.status} | ${r.duration_ms}ms |`);
  }
  lines.push(``);

  // Failed test details with snapshots
  const failures = results.results.filter((r) => r.status === "failed");
  if (failures.length > 0) {
    lines.push(`### 🔍 Failure Details`);
    lines.push(``);
    for (const f of failures) {
      lines.push(`<details>`);
      lines.push(`<summary>❌ ${f.name}</summary>`);
      lines.push(``);
      if (f.error) {
        lines.push(`**Error**: \`${f.error}\``);
        lines.push(``);
      }
      if (f.accessibility_snapshot) {
        lines.push(`**Page Snapshot** (accessibility tree at time of failure):`);
        lines.push(``);
        // Truncate very long snapshots
        const snap = f.accessibility_snapshot.length > 2000
          ? f.accessibility_snapshot.substring(0, 2000) + "\n... (truncated)"
          : f.accessibility_snapshot;
        lines.push("```yaml");
        lines.push(snap);
        lines.push("```");
      }
      lines.push(`</details>`);
      lines.push(``);
    }
  }

  // Generated files listing
  lines.push(`### 📁 Generated Test Files`);
  lines.push(``);
  for (const f of files) {
    lines.push(`- \`${f.path}\``);
  }
  lines.push(``);

  // Test plan
  lines.push(`### 📝 AI-Generated Test Plan`);
  lines.push(``);
  lines.push(`<details>`);
  lines.push(`<summary>Click to expand test plan</summary>`);
  lines.push(``);
  lines.push(testPlan);
  lines.push(``);
  lines.push(`</details>`);
  lines.push(``);

  // Footer
  lines.push(`---`);
  lines.push(`*This PR was created automatically by the SentinelQA pipeline.*`);
  lines.push(`*Tests were generated by the AI Architect agent and executed by the Playwright MCP server.*`);

  return lines.join("\n");
}
